---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "OAK TREE HOMEBUYERS | Cash For Your House"
keywords:    "oaktreehomebuyers, homebuyers, montgomery county, foreclosure, short sale, bankrupcy, pre-foreclosure, debt, debt reduction, debt services, upside down, probate, relocation, mortgage"
description: "OAK TREE HOMEBUYERS pays cash for your house. We buy homes in any condition in Montgomery County, PA"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-icon-72x72.png"
google_analytics_key: UA-69610849-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#ff0000'
  
