# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
# highlighter: pygments
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null


# Site settings
title:       "OAK TREE HOMEBUYERS | Cash For Your House"
keywords:    "oaktreehomebuyers, homebuyers, montgomery county, foreclosure, short sale, bankruptcy, pre-foreclosure, debt, debt reduction, debt services, upside down, probate, relocation, mortgage, two mortgages"
description: "OAK TREE HOMEBUYERS pays cash for your house. We buy homes in any condition in Montgomery, Delaware, and Chester Counties of Pennsylvania"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-icon-72x72.png"
google_analytics_key: UA-69610849-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#ff0000'

kramdown:
  auto_ids:  false
